[package]
#name = "mosquitto-rust-example"
name = "mqtt-auth-server"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["rt-multi-thread", "time", "macros"] }
url = "2.3.1"
paho-mqtt = "0.11.1"
anyhow = "1"
futures-util = "0.3.24"