[package]
name = "sweepers"
version = "0.1.0"
authors = ["JiaYe"]
edition = "2018"

[dependencies]
rand = "*"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }