[package]
name = "neat-sweepers"
version = "0.1.0"
authors = ["JiaYe"]
edition = "2018"

[dependencies]
rand = "0.6.5"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }