[package]
name = "client"
version = "1.0.0"
authors = ["Jia Ye <planet0104@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]

[profile.release]
lto = true
opt-level = 's'
panic = 'abort'
#opt-level = 's'
#panic = 'abort'